name: bet_u
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0   # ✅ 4.1.0 고정
  firebase_auth: ^6.0.2   # ✅ 6.0.2 고정
  smooth_page_indicator: ^1.2.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  tosspayments_widget_sdk_flutter: ^2.1.1
  intl: ^0.20.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets와 fonts는 동일한 들여쓰기 레벨이어야 합니다.
  assets:
    - assets/images/
    - assets/category/
    - assets/images/point/
    - assets/images/point/background/


    
  fonts:
    - family: Freesentation
      fonts:
        - asset: assets/fonts/Freesentation-3Light.ttf
          weight: 300
        - asset: assets/fonts/Freesentation-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Freesentation-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Freesentation-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Freesentation-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Freesentation-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Freesentation-9Black.ttf
          weight: 900
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
