// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7aFcZnFNn3Q6h6qINjZcImKaWezd5B4',
    appId: '1:413017569235:web:50d3888a1c4c0f484d2126',
    messagingSenderId: '413017569235',
    projectId: 'betu-522bb',
    authDomain: 'betu-522bb.firebaseapp.com',
    storageBucket: 'betu-522bb.firebasestorage.app',
    measurementId: 'G-BZ21WVNP6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqOmF-QOr1EXDvw1f4feTJyB883Emxj2E',
    appId: '1:413017569235:android:9772ffb1c2e607aa4d2126',
    messagingSenderId: '413017569235',
    projectId: 'betu-522bb',
    storageBucket: 'betu-522bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvCbz_LhYTpLOAbP2d6OaFq6nHiujvb8',
    appId: '1:413017569235:ios:ee27881f474c972d4d2126',
    messagingSenderId: '413017569235',
    projectId: 'betu-522bb',
    storageBucket: 'betu-522bb.firebasestorage.app',
    iosBundleId: 'com.example.betu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvCbz_LhYTpLOAbP2d6OaFq6nHiujvb8',
    appId: '1:413017569235:ios:ee27881f474c972d4d2126',
    messagingSenderId: '413017569235',
    projectId: 'betu-522bb',
    storageBucket: 'betu-522bb.firebasestorage.app',
    iosBundleId: 'com.example.betu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK7aFcZnFNn3Q6h6qINjZcImKaWezd5B4',
    appId: '1:413017569235:web:1086c23b0cde9fbd4d2126',
    messagingSenderId: '413017569235',
    projectId: 'betu-522bb',
    authDomain: 'betu-522bb.firebaseapp.com',
    storageBucket: 'betu-522bb.firebasestorage.app',
    measurementId: 'G-3BFJJ73B7G',
  );

}